spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: ecrh123456
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # redis配置
  data:
    redis:
      host: localhost
      port: 6379

# Mybatis配置：驼峰命名， log控制台输出
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# AliYunOSS配置
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t96UMZgbWfoa4WWywMe
    access-key-secret: DOyrX4cuE2a5fcl4Zh2rtWLLZeb9gr
    bucket-name: java-web-chm